version: "3.1"

services:
  db:
    image: mysql
    container_name: "mysqldb"
    restart: always
    environment:
      MYSQL_DATABASE: "$MYSQL_DB_NAME"
      MYSQL_USER: "MYSQL_DB_USERNAME"
      MYSQL_PASSWORD: "MYSQL_DB_PASSWORD"
      MYSQL_ROOT_PASSWORD: "$MYSQL_DB_PASSWORD"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  redis-server:
    hostname: redis
    container_name: "redisdb"
    image: 'redis'
    ports:
      - "6379:6379"

volumes:
  my-db:
