version: "3.1"

services:
  db:
    image: mysql
    container_name: "mysqldb"
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  redis-server:
    hostname: redis
    container_name: "redisdb"
    image: 'redis'
    ports:
      - "6379:6379"

volumes:
  my-db:

